# Builds a Docker image for use LNbits regtest scripts.
# Currenly works only for the forked version:
# fork: https://github.com/fusion44/legend-regtest-enviroment
# original: https://github.com/lnbits/legend-regtest-enviroment

FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
