[project]
name = "blitz_api"
version = "0.5.1"
description = "A backend for the Raspiblitz project"
authors = [{ name = "fusion44", email = "some.fusion@gmail.com" }]
requires-python = ">=3.11,<3.13"
license = "MIT"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]==0.120.4",
    "fastapi-plugins[redis]==0.14.0",
    "starlette==0.49.1",
    "anyio==4.9.0",
    "uvicorn[standard]==0.34.2",
    "pydantic==2.10.6",
    "pydantic-core==2.27.2",
    "typing-extensions==4.12.2",
    "pyjwt==2.10.1",
    "python-decouple==3.8",
    "psutil==7.0.0",
    "requests==2.32.4",
    "pyzmq==26.4.0",
    "aiohttp==3.13.3",
    "grpcio==1.71.0",
    "grpcio-tools==1.71.0",
    "protobuf==5.29.5",
    "deepdiff==8.6.1",
    "loguru==0.7.3",
    "celery[redis]==5.5.2",
    # Required for the fastapi-plugins[redis]
    # Maybe remove and use redis-py directly instead as this is deprecated
    "async_timeout==5.0.1",
]

[project.scripts]
api = "app.server:main"

[dependency-groups]
dev = [
    "pytest==8.3.5",
    "pytest-asyncio==0.25.3",
    "coverage==7.8.0",
    "ruff==0.9.6",
    "debugpy==1.8.14",
    "click==8.1.8",
    "watchfiles==0.24.0",
]

[tool.hatch.build.targets.sdist]
include = ["app"]

[tool.hatch.build.targets.wheel]
include = ["app"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.isort]
profile = "black"

[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F"]
ignore = []

# Allow auto fix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "app/lightning/impl/protos/*"
]

# Same as Black.
line-length = 88

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py311"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10
